let names = ['Sam', 'Tyler', 'Brook'];
let iterator = names[Symbol.iterator]();
let firstRun = iterator.next();
let name = firstRun.value;
console.log(name);
let secondRun = iterator.next();
name = secondRun.value;
console.log(name);
let thirdRun = iterator.next();
name = thirdRun.value;
console.log(name);